
stages:
  - build
  - deploy

compile-angular:
   stage: build
   tags:
      - activage
   cache:
      key: $CI_JOB_NAME
      paths:
         - node_modules/
   image: node:12
   before_script:
      - npm install
      - npm install -g @angular/cli
   script:
      - ng build
   artifacts:
      paths:
        - dist/codegenerator-ui
      expire_in: 1 hour

deploy:
  stage: deploy
  image: docker:dind
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSOWORD $DOCKER_SERVER 
    - docker build -t code.generator.ui -t $DOCKER_SERVER/code.generator.ui:$CI_COMMIT_REF_SLUG -t $DOCKER_SERVER/code.generator.ui:latest .
    - docker push $DOCKER_SERVER/code.generator:$CI_COMMIT_REF_SLUG
    - docker push $DOCKER_SERVER/code.generator.ui:latest

mirror-git:
  stage: deploy
  image:
    name: alpine/git
    entrypoint: ["/bin/sh", "-c"]
  cache: {}
  script:
    - git clone --mirror ${CI_REPOSITORY_URL} project
    - cd project
    - git remote add activage ${ACTIVAGE_PROJECT_URL}.git
    - git push --mirror activage
