version : "3.0"
services:
  codegenerator-backend:
    image: codegenerator-backend
    ports:
       - '8181:8181'
  codegenerator-frontend:
    image: codegenerator-frontend
    ports: 
      - '8080:80'
    environment: 
        - AIOTES_HOSTNAME=${AIOTES_HOSTNAME}
        - AIOTES_API_PORT=${AIOTES_API_PORT}
        - CODEGENERATOR_PATH=${CODEGENERATOR_PATH}