version : "3.0"
services:
  codegenerator:
    image: codegeneratorlocal
    ports:
       - '8181:8181'
  user-interface:
    build: .
    #image: docker-activage.satrd.es/code.generator.ui
    ports: 
      - '8080:80'
    environment: 
      - AIOTES_HOSTNAME=${AIOTES_HOSTNAME}
      - AIOTES_API_PORT=${AIOTES_API_PORT}
      - CODEGENERATOR_PATH=${CODEGENERATOR_PATH}